version: "3.8"
services:
  backend:
    image: mariazcona/distributedsystems24-backend:latest  # Usa el nombre y etiqueta correctos de tu imagen
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xmx512m

  frontend:
    image: mariazcona/distributedsystems24-frontend:latest  # Usa el nombre y etiqueta correctos de tu imagen
    ports:
      - "5000:5000"
    depends_on:
      - backend
    environment:
      - FLASK_ENV=development
      - BACKEND_URL=http://backend:8080
