version: "3.8"
services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080

  frontendflask:
    image: maeddes/frontendflask:hse24
    #build:
    #  context: ./frontend  # Assuming your frontend is in the 'frontend' directory
    environment:
      API_URL: "http://backendspringboot:8080/api/shopping"  # Use the API URL for communication between containers
    ports:
      - "5000:5000"
    depends_on:
      - backendmicronaut