micronaut:
  application:
    name: backend_app
  swagger:
    enabled: true
    endpoints:
      path: /swagger

server:
  port: ${SERVER_PORT:8080}
  cors:
    enabled: true
    mappings:
      "/**":
        allowedOrigins: "*"  
        allowedMethods: "GET, POST, PUT, DELETE"  
        allowedHeaders: "*"



