FROM python:3-alpine
WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 5000
ENV FLASK_ENV=development
CMD ["flask", "run", "--host", "0.0.0.0", "--port", "5000"]